Output only after filtering read assignments (minimap) [CW-5987]

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -102,8 +102,8 @@ docker-run:
           NF_WORKFLOW_OPTS: "--fastq test_data/case01 --classifier minimap2 --minimap2_by_reference --database_set ncbi_16s_18s --keep_bam --include_read_assignments"
           NF_IGNORE_PROCESSES: "extractMinimap2Reads,configure_igv,filter_references"
           AFTER_NEXTFLOW_CMD: >
-            if [ ! -f $$PWD/$$CI_PROJECT_NAME/reads_assignments/barcode01_lineages.minimap2.assignments.tsv ]; then (echo -e "Filtered assignments not found" && exit 1); fi &&
-            if [ ! -f $$PWD/$$CI_PROJECT_NAME/reads_assignments_unfiltered/barcode01.minimap2.assignments.tsv ]; then (echo -e "Raw assignments not found" && exit 1); fi
+            grep "Found empty file for sample 'barcode05'" .nextflow.log &&
+            if [ ! -f $$PWD/$$CI_PROJECT_NAME/reads_assignments/barcode01_lineages.minimap2.assignments.tsv ]; then (echo -e "Assignments not found" && exit 1); fi
 
 
      # Minimap2 - sample sheet - taxonomic_rank - taxa barplot - abundance_threshold
